import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Step 1: External Library (Required for both tags) */}
        <Script 
          id="aclib" 
          src="//acscdn.com/script/aclib.js" 
          strategy="beforeInteractive" 
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}

        {/* Step 2: Combined Zone Tags */}
        <Script id="adcash-tags" strategy="afterInteractive">
          {`
            // Original Tag
            aclib.runAutoTag({
                zoneId: 'silgmbd0e0',
            });

            // New Tag
            aclib.runAutoTag({
                zoneId: 'kfcnfnf80l',
            });
          `}
        </Script>
      </body>
    </html>
  );
}
